# TODO: customize your startup!
company:
  name: "Start It Up!"
  short_description: "Product based startup platform"
analytics:
  # google analytics id
  tracking_id: "UA-79006393-2"

status:
  launched: no